apiVersion: v2
name: kadalu
icon: https://kadalu.io/static/css/logo.png
description: Contains subchart for deploying Kadalu Operator and Kadalu CSI Nodeplugin
type: application
# Value of 'version' will be replaced with correct version on part of release
version: 0.0.0-0
dependencies:
  - name: common
    repository: file://charts/common
  - name: operator
    repository: file://charts/operator
    condition: operator.enabled
  - name: csi-nodeplugin
    repository: file://charts/csi-nodeplugin
    condition: csi-nodeplugin.enabled
