# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thank you for your contributions.

  Noticed that this issue is idle since 180 days! There is a possibility
  that this issue is already fixed in later releases. Please upgrade and
  check! If I don't hear any update in this issue in next 2 weeks, will
  be closing the issue.

  That doesn't mean one can't re-open the issue! Just comment on the
  issue, and click 'Reopen', if you still have the issue.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
