---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kadalu-csi-nodeplugin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: kadalu-csi-nodeplugin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kadalu-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
