apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: kadalu
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kadalu
  template:
    metadata:
      labels:
        name: kadalu
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8050"
    spec:
      serviceAccountName: kadalu-operator
      containers:
        - name: kadalu-operator
          securityContext:
            capabilities: {}
            privileged: true
          image: docker.io/kadalu/kadalu-operator:{{- if eq .Chart.Version "0.0.0-0" }}devel{{- else}}{{.Chart.Version}}{{- end }}
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kadalu-operator"
            - name: IMAGES_HUB
              value: "{{ .Values.imagesHub }}"
            - name: DOCKER_USER
              value: "kadalu"
            - name: KADALU_VERSION
              value: "{{- if eq .Chart.Version "0.0.0-0" }}devel{{- else}}{{.Chart.Version}}{{- end }}"
            - name: KADALU_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: KUBELET_DIR
              {{- if (eq .Values.kubernetesDistro "microk8s") }}
              value: "/var/snap/microk8s/common/var/lib/kubelet"
              {{- else }}
              value: "/var/lib/kubelet"
              {{- end }}
            - name: K8S_DIST
              value: "{{ .Values.kubernetesDistro }}"
            - name: VERBOSE
              value: "{{ .Values.verbose }}"
