apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kadalu
  template:
    metadata:
      labels:
        name: kadalu
        app.kubernetes.io/part-of: kadalu
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8050"
    spec:
      serviceAccountName: kadalu-operator
      containers:
        - name: kadalu-operator
          securityContext:
            capabilities: {}
            privileged: true
          image: {{ include "common.images.image" . }}/kadalu-operator:{{ include "common.version" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kadalu-operator"
            - name: IMAGES_HUB
              value: {{ .Values.global.image.registry | quote }}
            - name: DOCKER_USER
              value: {{ .Values.global.image.repository | quote }}
            - name: KADALU_VERSION
              value: {{ include "common.version" . | quote }}
            - name: KADALU_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: KUBELET_DIR
              value: {{ include "common.configs.kubeletDir" . | quote }}
            - name: K8S_DIST
              value: {{ .Values.global.kubernetesDistro | quote }}
            - name: VERBOSE
              value: {{ .Values.verbose | quote }}
