---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}
  {{- if (eq .Values.global.kubernetesDistro "openshift") }}
  labels:
    openshift.io/cluster-monitoring: "true"
  {{- end }}
