VERSION ?= "master"

help:
	@echo "make help        - Show this help message"
	@echo "make gen-version - Generate Version file based on Env variable"

gen-version:
	@echo "VERSION = \"${VERSION}\"" > kubectl_kadalu/version.py
