
= Setup Monitoring of Kadalu in Openshift & OKD 4.X clusters

This guide will assist you in collecting metrics & performance data into Openshift/OKD Prometheus.

== Enable user workload monitoring

Follow the official documentation for enabling user workload monitoring.
This is a sample from OKD4.10 and it should be used as a guidance only.
This effectively informs OKD in-cluster monitoring to scrape user workload endpoints as well.

```
# In this example we also use Kadalu as persistent storage of Prometheus.
# If you use another storage class for that -> set only "enableUserWorkload"
 
$ oc -n openshift-monitoring edit configmap cluster-monitoring-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s: 
      volumeClaimTemplate:
       metadata:
         name: prometheusdb
       spec:
         storageClassName: kadalu.gluster
         accessModes:
           - ReadWriteMany
         resources:
           requests:
             storage: 50Gi
    alertmanagerMain:
      volumeClaimTemplate:
       metadata:
         name: alertmanager
       spec:
         storageClassName: kadalu.gluster
         accessModes:
           - ReadWriteMany
         resources:
           requests:
             storage: 50Gi

== Apply the following manifest:
```
---
# Enables monitoring infra to scrape metrics from `kadalu` namespace
kind: Namespace
apiVersion: v1
metadata:
  name: kadalu
  labels:
    openshift.io/cluster-monitoring: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: operator
  namespace: kadalu
  labels:
    name: kadalu
spec:
  selector:
    name: kadalu
  ports:
    - name: kadalu-metrics
      protocol: TCP
      port: 8050
      targetPort: 8050
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kadalu-metrics
  namespace: kadalu
  labels:
    name: kadalu
spec:
  endpoints:
    - path: /metrics/
      port: kadalu-metrics
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      name: kadalu
---
# Enables monitoring infra to have necessary RBAC for scraping metrics in `kadalu` namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kadalu-metrics
  namespace: kadalu
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kadalu-metrics
  namespace: kadalu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kadalu-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
```

== Verify that the target is being scraped:

- Obtain the endpoints of the service
```
$ oc -n kadalu  describe  services operator | awk '/Endpoints/ {print "http://"$2}'
```

- Go to the UI -> Administrator -> Observe -> Targets

- Go to the UI -> Administrator -> Observe -> Metrics -> Type "kadalu_" -> There should be multiple metrics

== Alarm configuration

- Once the Metrics are visible in the UI, you can setup some alerts.


```
# Create and apply this manifest:
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kadalu-alert
  namespace: kadalu
        
spec:
  groups:
  - name: PVC-Space-alerts
    rules:
    - alert: PvcFreeSpaceLow
      annotations:
        description: PVC space is low!
      expr: kadalu_pvc_free_capacity_bytes < 1.073741824e+10
      labels:
        severity: warning
    - alert: PvcFreeSpaceCritical
      annotations:
        description: PVC space is critical!
      expr: kadalu_pvc_free_capacity_bytes < 0.536870912e+10
      labels:
        severity: critical
  - name: PVC-inode-alerts
    rules:
    - alert: PVCFreeInodesLow
      annotations:
        description: PVC Free inodes is low!
      expr: kadalu_pvc_free_inodes < 500000
      labels:
        severity: warning
    - alert: PVCFreeInodesCritical
      annotations:
        description: PVC Free inodes is critical!
      expr: kadalu_pvc_free_inodes < 200000
      labels:
        severity: critical
```
