
= Upgrade Kadalu

Here the steps to upgrade a Kadalu service from v0.8.1 to the latest version for Kubernetes.
It should apply to any newer upgrade.

== Upgrade kubectl-kadalu binary

[source,console]
----
$ curl -fsSL https://github.com/kadalu/kadalu/releases/latest/download/install.sh | sudo bash -x
$ kubectl-kadalu version
kubectl-kadalu 0.8.6
----

== Apply kadalu operator file

1. Download the relevant Kadalu Operator file definition according to your Kubernetes Cluster:
 - Generic Kubernetes: https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator.yaml[kadalu-operator.yaml]
 - MicroK8s: https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator-microk8s.yaml[kadalu-operator-microk8s.yaml]
 - RKE: https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator-rke.yaml[kadalu-operator-rke.yaml]
 - OpenShift: https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator-openshift.yaml[kadalu-operator-openshift.yaml]
2. Apply the file definition to the Kubernetes Cluster.

[source,console]
----
kubectl apply -f kadalu-operator.yaml
----

Exemple for a generic Kubernetes Cluster in single command ligne:

[source,console]
----
  curl -Ls https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator.yaml | sed -e 's/"no"/"yes"/g' | kubectl apply -f -
  
  namespace/kadalu unchanged
  serviceaccount/kadalu-operator unchanged
  serviceaccount/kadalu-csi-nodeplugin unchanged
  serviceaccount/kadalu-csi-provisioner unchanged
  serviceaccount/kadalu-server-sa unchanged
  customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage configured
  clusterrole.rbac.authorization.k8s.io/pod-exec unchanged
  clusterrole.rbac.authorization.k8s.io/kadalu-operator unchanged
  clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator unchanged
  deployment.apps/operator configured
----

(wait for operator and csi-provisionner pods in kadalu namespace get in Running state)

== Apply kadalu CSI-Nodeplugin

1. Download the relevant Kadalu CSI-Nodeplugin file definition according to your Kubernetes Cluster:
 - Generic Kubernetes: https://github.com/kadalu/kadalu/releases/latest/download/csi-nodeplugin.yaml[csi-nodeplugin.yaml]
 - MicroK8s: https://github.com/kadalu/kadalu/releases/latest/download/csi-nodeplugin-microk8s.yaml[csi-nodeplugin-microk8s.yaml]
 - RKE: https://github.com/kadalu/kadalu/releases/latest/download/csi-nodeplugin-rke.yaml[csi-nodeplugin-rke.yaml]
 - OpenShift: https://github.com/kadalu/kadalu/releases/latest/download/csi-nodeplugin-openshift.yaml[csi-nodeplugin-openshift.yaml]
2. Apply the file definition to the Kubernetes Cluster.

[source,console]
----
kubectl apply -f csi-nodeplugin.yaml
----

Exemple for a generic Kubernetes Cluster in single command line:

[source,console]
----
curl -Ls https://github.com/kadalu/kadalu/releases/latest/download/csi-nodeplugin.yaml | sed -e 's/"no"/"yes"/g' | kubectl apply -f -

clusterrole.rbac.authorization.k8s.io/kadalu-csi-nodeplugin unchanged
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-nodeplugin unchanged
daemonset.apps/kadalu-csi-nodeplugin configured
----

Wait for the kadalu-csi-nodeplugin* pod got all replaced and get in Running state: it can take time since there's 1 pod per node and kadalu upgrade them one at a time
