apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kadalu
spec:
  version: "v{{ .TagName }}"
  homepage: https://github.com/kadalu/kadalu
  shortDescription: "Deploy and manage Kadalu Operator, CSI and Storage pods"
  description: |
    Kadalu project offers a lightweight Persistent storage solution
    for applications running in Kubernetes.

    kubectl-kadalu helps to install Kadalu Operator and provides
    sub-commands to manage/monitor Kadalu Storage pods.

  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    {{addURIAndSha "https://github.com/kadalu/kadalu/releases/download/{{ .TagName }}/kubectl-kadalu.tar.gz" .TagName }}
    bin: kubectl-kadalu
    files:
    - from: kubectl-kadalu
      to: .
    - from: LICENSE
      to: .
