#!/usr/bin/python3
import os
import sys
import json

from jinja2 import Template

info_dir = "/var/lib/gluster"
templates_dir = "/kadalu/templates"
volfiles_dir = "/kadalu/volfiles"

volname = sys.argv[1]

info_file = os.path.join(info_dir, "%s.info" % volname)
data = {}
with open(info_file) as f:
    data = json.load(f)

# Tricky to get this right, but this solves all the elements of distribute in code :-)
data['dht_subvol'] = []
if data["type"] == "Replica1":
    for brick in data["bricks"]:
        data["dht_subvol"].append("%s-client-%d" % (data["volname"], brick["brick_index"]))
else:
    count = 3
    if data["type"] == "Replica2":
        count = 2
    for i in range(0, int(len(data["bricks"]) / count)):
        data["dht_subvol"].append("%s-replica-%d" % (data["volname"], i))

template_file = os.path.join(templates_dir, "%s.client.vol" % data["type"])
client_volfile = os.path.join(volfiles_dir, "%s.client.vol" % volname)
content = ""
with open(template_file) as f:
    content = f.read()

Template(content).stream(**data).dump(client_volfile)

os.makedirs("/mnt/%s" % volname)

os.execv(
    "/opt/sbin/glusterfs",
    [
        "/opt/sbin/glusterfs",
        "--process-name", "fuse",
        "--volfile-id=%s" % volname,
        "-f", client_volfile,
        "/mnt/%s" % volname
    ]
)
