#!/usr/bin/python3
import os
import sys
import json

from serverutils import generate_client_volfile

INFO_DIR = "/var/lib/gluster"
VOLFILES_DIR= "/kadalu/volfiles"

volname = sys.argv[1]

info_file = os.path.join(INFO_DIR, "%s.info" % volname)
data = {}
with open(info_file) as f:
    data = json.load(f)

client_volfile_path = os.path.join(VOLFILES_DIR, "%s.client.vol" % volname)

generate_client_volfile(data, client_volfile_path)

os.makedirs("/mnt/%s" % volname)

os.execv(
    "/opt/sbin/glusterfs",
    [
        "/opt/sbin/glusterfs",
        "--process-name", "fuse",
        "--volfile-id=%s" % volname,
        "--fs-display-name", "kadalu:%s" % volname,
        "-f", client_volfile_path,
        "/mnt/%s" % volname
    ]
)
