# -*- mode: yaml -*-
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
spec:
  type: Replica1
  storage:
    - node: minikube           # node name as shown in `kubectl get nodes`
      device: /mnt/DISK/file1

---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-2
spec:
  type: Replica3
  storage:
    - node: minikube           # node name as shown in `kubectl get nodes`
      device: /mnt/DISK/file3.1
    - node: minikube           # node name as shown in `kubectl get nodes`
      device: /mnt/DISK/file3.2
    - node: minikube           # node name as shown in `kubectl get nodes`
      device: /mnt/DISK/file3.3
