# -*- mode: yaml -*-
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv4-1
  labels:
    type: disperse
spec:
  storageClassName: kadalu.storage-pool-4
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod4-1
  labels:
    app: sample-app
    type: disperse
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv4-1
  restartPolicy: OnFailure

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv4-2
  labels:
    type: disperse
spec:
  storageClassName: kadalu.storage-pool-4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod4-2
  labels:
    app: sample-app
    type: disperse
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv4-2
  restartPolicy: OnFailure
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.storage-pool-4-virtblock
allowVolumeExpansion: true
provisioner: kadalu
parameters:
  storage_name: "storage-pool-4"
  pv_type: Block
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv4-3
  labels:
    type: disperse
spec:
  storageClassName: kadalu.storage-pool-4-virtblock
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4-3
  labels:
    app: sample-app
    type: disperse
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv4-3
  restartPolicy: OnFailure
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv4-4
  labels:
    type: disperse
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: kadalu.storage-pool-4
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4-4
  labels:
    type: disperse
spec:
  containers:
    - name: bash-block-vol
      image: bash
      command: ["/usr/local/bin/bash","-c"]
      args: ["echo sample text > /tmp/original && dd if=/tmp/original of=/dev/xvda && dd if=/dev/xvda of=/tmp/copy bs=1 count=12 && cat /tmp/{original,copy} && diff <(cat /tmp/original) <(cat /tmp/copy) && echo all good"]
      volumeDevices:
        - devicePath: /dev/xvda
          name: csivol4
      imagePullPolicy: IfNotPresent
  volumes:
    - name: csivol4
      persistentVolumeClaim:
        claimName: pv4-4
  restartPolicy: OnFailure
