# -*- mode: yaml -*-
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
spec:
  type: Replica1
  storage:
    - node: minikube      # node name as shown in `kubectl get nodes`
      device: /mnt/vda1/device # Device to provide storage to all PVs

      # Optionally, path can be specified to provide storage
      # directory directly. Note: Directory should support xattrs
      # and project quota support(Ex: xfs). For example,
      # path: /exports/data
