# -*- mode: yaml -*-
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1-1
spec:
  storageClassName: kadalu.storage-pool-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
# -*- mode: yaml -*-
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1-2
spec:
  storageClassName: kadalu.storage-pool-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
# -*- mode: yaml -*-
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-1
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv1-1
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-2
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol1
  volumes:
  - name: csivol1
    persistentVolumeClaim:
      claimName: pv1-2
  restartPolicy: OnFailure
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.storage-pool-1-virtblock
provisioner: kadalu
parameters:
  storage_name: "storage-pool-1"
  pv_type: Block
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1-3
spec:
  storageClassName: kadalu.storage-pool-1-virtblock
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-3
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol2
  volumes:
  - name: csivol2
    persistentVolumeClaim:
      claimName: pv1-3
  restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1-4
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: kadalu.storage-pool-1
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-4
spec:
  containers:
    - name: bash-block-vol
      image: bash
      command: ["/usr/local/bin/bash","-c"]
      args: ["echo sample text > /tmp/original && dd if=/tmp/original of=/dev/xvda && dd if=/dev/xvda of=/tmp/copy bs=1 count=12 && cat /tmp/{original,copy} && diff <(cat /tmp/original) <(cat /tmp/copy) && echo all good"]
      volumeDevices:
        - devicePath: /dev/xvda
          name: csivol4
      imagePullPolicy: IfNotPresent
  volumes:
    - name: csivol4
      persistentVolumeClaim:
        claimName: pv1-4
  restartPolicy: OnFailure
