# -*- mode: yaml -*-
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1-1
spec:
  storageClassName: kadalu.replica1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
# -*- mode: yaml -*-
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv1-2
spec:
  storageClassName: kadalu.replica1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
# -*- mode: yaml -*-
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-1
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv1-1
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-2
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol1
  volumes:
  - name: csivol1
    persistentVolumeClaim:
      claimName: pv1-2
  restartPolicy: OnFailure
