---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.external.test  # Keep changing the name for different volumes
provisioner: kadalu
parameters:
  hostvol_type: "External-Kadalu"
  gluster_host: gluster1.kadalu.io   # Change to your gluster host
  gluster_volname: kadalu            # Change to existing gluster volume
  gluster_options: log-level=DEBUG   # Comma separated options

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-ext-kadalu
spec:
  storageClassName: kadalu.external.test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Mi # This needs to be set using 'kadalu-quotad'

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-ext-kadalu
  labels:
    app: sample-app
spec:
  containers:
  - name: sample-app
    image: docker.io/kadalu/sample-pv-check-app:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/pv"
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
      claimName: pv-ext-kadalu
  restartPolicy: OnFailure
