# -*- mode: yaml -*-
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
spec:
  type: Replica1
  storage:
    - node: minikube           # node name as shown in `kubectl get nodes`
      device: /mnt/DISK/file1

---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-2
spec:
  type: Replica3
  storage:
    - node: minikube            # node name as shown in `kubectl get nodes`
      device: /mnt/DISK/file3.1 # file as a device
    - node: minikube            # node name as shown in `kubectl get nodes`
      path: /mnt/DISK/dir3.2    # Using a path from host
    - pvc: local-pvc            # PVC belonging to this namespace, no 'node'
                                #required when there is PVC
