apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kadalu
spec:
  version: "v0.8.7"
  homepage: https://github.com/kadalu/kadalu
  shortDescription: "Deploy and manage Kadalu Operator, CSI and Storage pods"
  description: |
    Kadalu project offers a lightweight Persistent storage solution
    for applications running in Kubernetes.

    kubectl-kadalu helps to install Kadalu Operator and provides
    sub-commands to manage/monitor Kadalu Storage pods.

  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    uri: https://github.com/kadalu/kadalu/releases/download/0.8.7/kubectl-kadalu.tar.gz
    sha256: d0d754d6e4e08f7a09f25913bf787e9da5944488b7f630cc57d99655dc2b242b
    bin: kubectl-kadalu
