name: Docker

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - "*"

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Run 'make release'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          KADALU_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }} make release
