name: buildx

on:
  push:
    branches:
      - devel
      - buildx_test
# Add tags later (for pushing release)

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      -
        name: Set up Docker Buildx
        if: success()
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Set up Python (for cli-build)
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Get the CLI build (kubectl-kadalu)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          KADALU_VERSION=devel make cli-build
      -
        name: Run Buildx
        if: success()
        time_minutes: 144
        run: |
          KADALU_VERSION=devel docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag docker.io/kadalu/kadalu-base:latest \
            --output "type=image,name=docker.io/kadalu/kadalu-base,push=false" \
            --file operator/Dockerfile.base .
          KADALU_VERSION=devel docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag docker.io/kadalu/kadalu-csi:devel \
            --output "type=image,name=docker.io/kadalu/kadalu-csi,push=true" \
            --file csi/Dockerfile .
          KADALU_VERSION=devel docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag docker.io/kadalu/kadalu-operator:devel \
            --output "type=image,name=docker.io/kadalu/kadalu-operator,push=true" \
            --file operator/Dockerfile .
          KADALU_VERSION=devel docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag docker.io/kadalu/kadalu-server:devel \
            --output "type=image,name=docker.io/kadalu/kadalu-server,push=true" \
            --file server/Dockerfile .
