name: PyPi images

on:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  multi-arch-build-for-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Python (for cli-build)
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      -
        name: Build PyPi Image
        uses: docker/build-push-action@v2
        timeout-minutes: 260
        with:
          context: .
          file: extras/Dockerfile.python-packages
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/kadalu/pypi_source:latest
          build-args: |
            version=latest
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=latest
