name: Run on every PR

on:
  pull_request:
    branches:
      - devel
    paths-ignore:
      - 'doc/**'
      - 'extras/**'
      - '**.md'

jobs:
  pylint:
    name: Run pylint
    runs-on: ubuntu-latest
    # Skip based on commit message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies pylint
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint glustercli
    - name: Run pylint
      run: make pylint

  run-on-minikube:
    name: kube 1.20.0
    runs-on: ubuntu-latest
    env:
      KUBE_VERSION: v1.20.0
    # Skip based on commit message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install Docker Dependencies
      run: sudo apt-get install -y conntrack
    - name: Build locally
      run: make build-containers
    - name: Generate Manifests
      run: VERBOSE="true" make gen-manifest
    - name: Setup Minikube
      run: tests/setup.sh $KUBE_VERSION
    - name: Run tests
      run: tests/travis-test.sh $KUBE_VERSION
    - name: Cleanup
      run: tests/cleanup.sh $KUBE_VERSION

      # Deploy KaDalu via Helm and run tests if PR address Helm charts
    - name: Setup Minikube for Helm Charts
      if: "contains(github.event.head_commit.message, '[helm]')"
      run: tests/setup.sh $KUBE_VERSION
    - name: Run tests
      if: "contains(github.event.head_commit.message, '[helm]')"
      run: tests/travis-test.sh $KUBE_VERSION
      env:
        INSTALL_TYPE: helm
    - name: Cleanup
      if: "contains(github.event.head_commit.message, '[helm]')"
      run: tests/cleanup.sh $KUBE_VERSION
