name: "On Pull Request"

on:
  pull_request:
    branches:
      - devel
    paths-ignore:
      - 'doc/**'
      - 'extras/**'
      - '!extras/Dockerfile.builder'
      - '**.md'

# Skip based on commit msg is inbuilt into Github Runner
# Visit: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

jobs:
  # Primarily used to save info required for any jobs/steps
  get-info:
    name: Save required info
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.info.outputs.FILES }}
      msg: ${{ steps.info.outputs.MSG }}
      build_base: ${{ steps.info.outputs.BUILD_BASE }}
      containers_for: ${{ steps.info.outputs.CONTAINERS_FOR }}
    steps:
      - id: info
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo FILES=$FILES >> $GITHUB_OUTPUT

          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits"
          MSG=$(curl -s -X GET -G $URL | jq -r '.[] | .commit.message')
          echo MSG=$MSG >> $GITHUB_OUTPUT

          BUILD_BASE="no"
          # build base image if one of below conditions is met
          # 1. if we have only CHANGELOG.md update (basically getting ready for a release)
          if grep -e 'CHANGELOG.md' <<< "$FILES" && [ $(wc -w <<< "$FILES") == 1 ]; then
            BUILD_BASE="yes"
          # 2. if builder dockerfile is edited
          elif grep -e 'extras/Dockerfile.builder' <<< "$FILES"; then
            BUILD_BASE="yes"
          fi
          echo BUILD_BASE=$BUILD_BASE >> $GITHUB_OUTPUT

          # Conditionally build test containers if PR includes tests/**/Dockerfile
          CONTAINERS_FOR=""
          if grep -e '\btests.*Dockerfile\b' <<< "$FILES"; then
            CONTAINERS_FOR=TESTING
          fi
          echo CONTAINERS_FOR=$CONTAINERS_FOR >> $GITHUB_OUTPUT

  pylint:
    name: Run pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'
        cache: 'pip'
        cache-dependency-path: 'requirements/ci_*.txt'

    - name: Install dependencies pylint
      run: |
          python -m pip install --upgrade --upgrade-strategy eager -r requirements/ci_submit-requirements.txt -r requirements/ci_merge-requirements.txt -e ./requirements

    - name: Run pylint
      run: make pylint

  run-on-k3d:
    name: Build and test
    runs-on: ubuntu-latest
    needs: get-info
    env:
      COMMIT_MSG: ${{needs.get-info.outputs.msg}}
      FILES: ${{needs.get-info.outputs.files}}
      BUILD_BASE: ${{needs.get-info.outputs.build_base}}
      CONTAINERS_FOR: ${{needs.get-info.outputs.containers_for}}
      K3D_VERSION: v5.6.3
      KUBE_IMG: rancher/k3s:v1.29.4-k3s1
      TARGZ_PATH: /tmp/images.tar.gz
    steps:
    - uses: actions/checkout@v4
    - name: Install Docker Dependencies
      run: sudo apt-get install -y conntrack ruby

    # CLI Tests
    - name: Install Binnacle and build kubectl-kadalu
      run: |
        # Temporary until https://github.com/kadalu/binnacle/issues/44
        curl -L https://github.com/kadalu/binnacle/releases/download/0.6.1/binnacle -o binnacle
        chmod +x ./binnacle
        sudo mv ./binnacle /usr/local/bin/binnacle
        binnacle --version
        make cli-build
    - name: kubectl-kadalu Tests
      run: binnacle -v cli/tests/storage_add.t

    # Restore Docker Images cache
    - name: Restore image cache
      uses: actions/cache/restore@v4
      with:
        path: $TARGZ_PATH
        key: images
        # Cache may not be found or name can be unknow since it was generated
        # in previous run
        restore-keys: images

    # Build Containers
    - name: Build locally
      run: |
        if [[ -f $TARGZ_PATH ]]; then
           pigz -dc $TARGZ_PATH | docker image load
        fi

        BUILD_BASE="$BUILD_BASE" make build-containers;
        if [[ "$CONTAINERS_FOR" == "TESTING" ]]; then
          make test-containers
        fi
        echo Completed building containers
    - name: Generate Manifests
      run: |
        # TODO: add a step to verify no uncommited changes in manifests
        VERBOSE="yes" make gen-manifest

    # Operator Tests
    - name: Run tests
      run: sudo -E tests/tests.sh

    - name: Save images
      id: save
      run: |
        # TODO: fix explicitly pulling base image here
        # base image for kadalu containers. This will be pulled when building containers already.
        docker pull $(grep prod kadalu_operator/Dockerfile | awk '{print $2}')

        # Save the images matching the pattern
        IMAGES=$(docker images --format "{{.Repository}}" | \
          grep -E 'kadalu/builder|rancher|raspbernetes|k3d|python' | sort -u | \
          xargs -i sh -c "docker images {} --format '{{.ID}}' | head -n1")
        HASH=$(echo -n $IMAGES | md5sum | awk '{print $1}')
        docker image save $(echo -n $IMAGES) | pigz --fast > $TARGZ_PATH
        echo HASH=$HASH >> $GITHUB_OUTPUT

    - name: Save image cache
      uses: actions/cache/save@v4
      with:
        key: images-${{ steps.save.outputs.HASH }}
        # TODO: nuke the cache after every release
        path: $TARGZ_PATH
