name: Release

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - "*"

env:
  kadalu_version: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')


jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  push-to-pypi-store:
    name: Push to pypi (quotad)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Run 'make release'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          KADALU_VERSION=${{ env.kadalu_version }} TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }} make pypi-upload

  publish-artifacts:
    name: Publish kubectl-kadalu, manifest files and helm charts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build kubectl-kadalu
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          KADALU_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make cli-build
    - name: Generate Manifests
      run: |
          KADALU_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make prepare-release-manifests
    - name: Upload Manifest files
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: manifests/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Upload kubectl-kadalu to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cli/build/kubectl-kadalu*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - uses: actions/checkout@v2
    - name: Generate tgz archive of Helm Chart
      run: |
        KADALU_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make helm-chart
    - name: Upload Helm Chart archive to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: helm/kadalu-helm-chart.tgz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  multi-arch-build-for-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version variable
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Python (for cli-build)
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Get the CLI build (kubectl-kadalu)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          KADALU_VERSION=${{ env.kadalu_version }} make cli-build
      -
        name: Build Builder Image
        uses: docker/build-push-action@v2
        timeout-minutes: 260
        with:
          context: .
          file: extras/Dockerfile.builder
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/kadalu/builder:latest
          build-args: |
            version=${{ steps.vars.outputs.tag }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ steps.vars.outputs.tag }}
      -
        name: Build CSI Image and push
        uses: docker/build-push-action@v2
        timeout-minutes: 200
        with:
          context: .
          file: csi/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-csi:${{ steps.vars.outputs.tag }}
            docker.io/kadalu/kadalu-csi:latest
          build-args: |
            version=${{ steps.vars.outputs.tag }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ steps.vars.outputs.tag }}
      -
        name: Build Operator Image and push
        uses: docker/build-push-action@v2
        timeout-minutes: 120
        with:
          context: .
          file: operator/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-operator:${{ steps.vars.outputs.tag }}
            docker.io/kadalu/kadalu-operator:latest
          build-args: |
            version=${{ steps.vars.outputs.tag }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ steps.vars.outputs.tag }}
      -
        name: Build Storage Server Image and push
        uses: docker/build-push-action@v2
        timeout-minutes: 120
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-server:${{ steps.vars.outputs.tag }}
            docker.io/kadalu/kadalu-server:latest
          build-args: |
            version=${{ steps.vars.outputs.tag }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ steps.vars.outputs.tag }}
