name: Kubectl-kadalu and Manifest files

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - "*"

jobs:
  build:
    name: Publish kubectl-kadalu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Generate Manifests
      run: |
          KADALU_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make prepare-release-manifests
    - name: Build kubectl-kadalu
      run: |
          python -m pip install --upgrade pip
          KADALU_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make cli-build
    - name: Upload Manifest files
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: manifests/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Upload kubectl-kadalu to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cli/build/kubectl-kadalu
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
